const {promo_token} = require('./app.json');
const LocalStrategy = require('passport-local').Strategy;
//const FacebookStrategy=require('passport-facebook').Strategy;//zum Teufel

module.exports = (db, passport)=>{

passport.serializeUser((user,done)=>{
	console.log('in serialize USERA: ',user);
done(null,user.id)
})

passport.deserializeUser(async (id, done)=>{
	console.log("IN deSerialize ", id);
	done(null,{user:"dima", id: 1, role:"admin"})
try{
//const luser = await db.query('select id, bname, brole from buser where id=$1', [ id ])

}catch(e){
done(e)
}
})

passport.use(new LocalStrategy({usernameField:'username',passwordField:'password'}, (username, password, done)=>{
	console.log("USERNAME AND PASSWORD: ",username,password);
	/*try{ 
     let user = await db.query('select id from buser where bname=$1 and pwd=$2',[username, password]) 
if(!user.rows[0]){
	return done(null, false, {message:'Неправильный ник или пароль! Wrong nickname or password!'})}
	 

await db.query('update buser set ll=now() where bname=$1', [username]); 
return done(null,user.rows[0],{message: 'Авторизация прошла успешно! Successful! ', nick: username, id: user.rows[0].id}) 
	}catch(err){
		return done(err)
		} 
*/
//return done(null, {user: username, id: 1},{message:"ok", status:200})
return done(null, false, {message:'Wrong nickname or password!', status:401 })
	}))


passport.use('local-signup', new LocalStrategy({usernameField: 'username', passReqToCallback: true}, async(req,username, password, done)=>{
if(!req.body.username || !password){return done(null,false,{message: "Missing credentials", status: 401 })}	
//process.nextTick(async()=>{
try{
	console.log(username,password);
	console.log('req.body: ', req.body);
	//console.log('email? :', req.body.email)
var useri = await db.collection('users').findOne({'name': username });
//await db.query(get_str({ password:'$1', username:'$2', email:'$3' }),[ password, req.body.username, req.body.email ])
console.log('USER.rows[0]: ', useri)
if(!useri) {
	console.log("Not found user")
	let qu = await db.collection('users').insertOne({name: username, pwd: password, role:'buser',ef: 0, b: 0});
	console.log('qu: ', qu);
}
return done(null, false, { message: "Username already in use!", status: 401 })
//return done(null,useri.rows[0],{message: smsg, username: username,user_id:useri.rows[0].id, email:req.body.email })
}catch(err){
	console.log('custom error handling in local signup auth.js: ', err.message);

		
	return done(null, false, { message: err, status: 401 })
	
}				 

}))
}
/*
 * alter table buser alter column id add generated by default as identity;
`You're almost finished.<br><br>
We've sent an account activation email to you at <strong>the fuck you do</strong>.
Head over to your inbox and click on the "Activate My Account" button to validate your email address.*/
